logging:
  level:
    org:
      springframework:
        jdbc:
         core: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/milkman
    username: postgres
    password: testpassword
    initialization-mode: always

server:
  servlet:
    contextPath: /milkman
  port: 8081