logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/milkman
    username: postgres
    password: Welcome@1234
    initialization-mode: always

server:
  servlet:
    contextPath: /milkman
  port: 8081